# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Phil Bottomley
description:      'Software Engineer in Leeds.'
url:              http://philbottomley.com
baseurl:          /

author:
  name:           'Phil Bottomley'
  url:            https://twitter.com/philbotto

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:             [jekyll-paginate, jekyll-gist]
